version: "3.7"
services:
  rinstat:
    # build: .
    image: istride/r-instat:0.2.0
    environment:
      DISPLAY: ${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/rinstat/.Xauthority
      - ~/Desktop:/home/rinstat/Desktop
    network_mode: host
    command:
      - mono
      - instat.exe
