version: "3.8"
services:
  rinstat:
    build: .
    environment:
      DISPLAY: ${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/rinstat/.Xauthority
    network_mode: host
    command:
      - mono
      - instat.exe
